import { PrismaClient } from "@prisma/client";

const fciBreeds = [
  "Affenpinscher",
  "Afgano",
  "Airedale Terrier",
  "Akita",
  "Malamute do Alasca",
  "Akita Americano",
  "Bulldog Americano",
  "Cocker Spaniel Americano",
  "Foxhound Americano",
  "Staffordshire Terrier Americano",
  "Cão de Pastor da Anatólia",
  "Appenzeller",
  "Dogo Argentino",
  "Ariegeois",
  "Artois Hound",
  "Boiadeiro Australiano",
  "Kelpie Australiano",
  "Pastor Australiano",
  "Silky Terrier Australiano",
  "Terrier Australiano",
  "Cão de Caça Austríaco Preto e Amarelo",
  "Pinscher Austríaco",
  "Azawakh",
  "Cão de Caça dos Balcãs",
  "Barbet",
  "Basenji",
  "Basset Artésien Normand",
  "Basset Bleu de Gascogne",
  "Basset Fauve de Bretagne",
  "Basset Hound",
  "Bavarian Mountain Hound",
  "Beagle",
  "Beagle Harrier",
  "Bearded Collie",
  "Beauceron",
  "Bedlington Terrier",
  "Griffon Belga",
  "Pastor Belga",
  "Cão Pastor Bergamasco",
  "Beauceron",
  "Berger Picard",
  "Sabujos Berneses",
  "Cão de Montanha Bernês",
  "Bichon Frisé",
  "Billy",
  "Coonhound Preto e Castanho",
  "Black and Tan Terrier",
  "Terrier Preto da Rússia",
  "Bloodhound",
  "Pastor Boêmio",
  "Bolognese",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Cão Pastor da Bósnia",
  "Boston Terrier",
  "Bouvier des Ardennes",
  "Bouvier des Flandres",
  "Boxer",
  "Bracco Italiano",
  "Braque d'Auvergne",
  "Braque du Bourbonnais",
  "Braque Français",
  "Braque Saint-Germain",
  "Terrier Brasileiro",
  "Briard",
  "Spaniel Bretão",
  "Broholmer",
  "Cão Bruno do Jura",
  "Pastor Bucovina",
  "Bull Terrier",
  "Bulldog",
  "Bullmastiff",
  "Cairn Terrier",
  "Cão de Canaã",
  "Cão Esquimó Canadense",
  "Cane Corso",
  "Canis Panther",
  "Cão de Castro Laboreiro",
  "Cão Fila de São Miguel",
  "Pastor Carpatiano",
  "Catahoula Leopard Dog",
  "Pastor Catalão",
  "Pastor Caucasiano",
  "Cão Pastor da Ásia Central",
  "Cesky Fousek",
  "Cesky Terrier",
  "Retriever Chesapeake Bay",
  "Chihuahua",
  "Cão de Crista Chinês",
  "Shar-Pei Chinês",
  "Chow Chow",
  "Cimarrón Uruguaio",
  "Cirneco do Etna",
  "Clumber Spaniel",
  "Collie",
  "Coton de Tulear",
  "Pastor Croata",
  "Retriever de Pelo Encaracolado",
  "Cão Lobo Checoslovaco",
  "Dachshund",
  "Dálmata",
  "Dandie Dinmont Terrier",
  "Cão de Fazenda Dinamarquês-Sueco",
  "Deerhound",
  "Dingo",
  "Dobermann",
  "Dogo Argentino",
  "Dogue de Bordeaux",
  "Drentse Patrijshond",
  "Drever",
  "Pastor Holandês",
  "Dutch Smoushond",
  "Laika da Sibéria Oriental",
  "Bulldog Inglês",
  "Cocker Spaniel Inglês",
  "Foxhound Inglês",
  "Mastiff Inglês",
  "Pointer Inglês",
  "Setter Inglês",
  "Pastor Inglês",
  "Springer Spaniel Inglês",
  "Entlebucher Mountain Dog",
  "Cão de Caça Estoniano",
  "Cão de Montanha da Estrela",
  "Eurasier",
  "Field Spaniel",
  "Fila Brasileiro",
  "Cão de Caça Finlandês",
  "Cão Lapão da Finlândia",
  "Spitz Finlandês",
  "Retriever de Pelo Liso",
  "Bulldog Francês",
  "Spaniel Francês",
  "Galgo Espanhol",
  "Gascon Saintongeois",
  "Pastor Georgiano",
  "Terrier de Caça Alemão",
  "Ponter Alemão de Pelo Longo",
  "Pinscher Alemão",
  "Pastor Alemão",
  "Ponter Alemão de Pelo Curto",
  "Spaniel Alemão",
  "Spitz Alemão",
  "Ponter Alemão de Pelo Duro",
  "Schnauzer Gigante",
  "Glen of Imaal Terrier",
  "Golden Retriever",
  "Setter Gordon",
  "Grand Anglo-Français",
  "Grand Basset Griffon Vendéen",
  "Grand Bleu de Gascogne",
  "Grand Griffon Vendéen",
  "Dog Alemão",
  "Grande Cão da Suíça",
  "Cão de Caça Grego",
  "Cão da Groenlândia",
  "Greyhound",
  "Griffon Bruxellois",
  "Griffon Nivernais",
  "Groenendael",
  "Gull Dong",
  "Cão de Caça Halden",
  "Cão de Caça Hamilton",
  "Sabujo de Hanôver",
  "Harrier",
  "Havanês",
  "Cão Pastor do Himalaia",
  "Hokkaido",
  "Hovawart",
  "Galgo Húngaro",
  "Cão de Caça Húngaro",
  "Kuvasz Húngaro",
  "Puli Húngaro",
  "Vizsla Húngaro",
  "Podengo Ibicenco",
  "Cão de Pastor Islandês",
  "Irish Glen of Imaal Terrier",
  "Setter Irlandês Vermelho e Branco",
  "Setter Irlandês",
  "Terrier Irlandês",
  "Spaniel de Água Irlandês",
  "Wolfhound Irlandês",
  "Istrian Shorthaired Hound",
  "Desconhecido",
];

const main = async () => {
  const prisma = new PrismaClient();

  await prisma.petBreed.createMany({
    data: fciBreeds.map((breed) => ({
      name: breed,
    })),
  });

  const breeds = await prisma.petBreed.findMany();
  console.log(JSON.stringify(breeds));
};

main().catch(console.error);
